# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 12:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fobi', '0015_auto_20180130_0013'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0015_auto_20180304_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedEventFormDataEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_data_headers', models.TextField(blank=True, null=True, verbose_name='Form data headers')),
                ('saved_data', models.TextField(blank=True, null=True, verbose_name='Plugin data')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('form_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fobi.FormEntry', verbose_name='Form')),
                ('invitee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.EventInvitee', verbose_name='Invitee')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Saved form data entry',
                'verbose_name_plural': 'Saved form data entries',
                'db_table': 'savedeventformdataentry',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SavedEventFormWizardDataEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_data_headers', models.TextField(blank=True, null=True, verbose_name='Form data headers')),
                ('saved_data', models.TextField(blank=True, null=True, verbose_name='Plugin data')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('form_wizard_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fobi.FormWizardEntry', verbose_name='Form')),
                ('invitee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.EventInvitee', verbose_name='Invitee')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Saved form wizard data entry',
                'verbose_name_plural': 'Saved form wizard data entries',
                'db_table': 'savedeventformwizarddataentry',
                'abstract': False,
            },
        ),
    ]
