# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-20 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events_form_database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedeventformdataentry',
            name='answer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='events_form_database.SavedEventFormDataEntry'),
        ),
        migrations.AddField(
            model_name='savedeventformwizarddataentry',
            name='answer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='events_form_database.SavedEventFormWizardDataEntry'),
        ),
    ]
