# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-21 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_form_database', '0002_auto_20180320_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedeventformdataentry',
            name='answer',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='savedeventformwizarddataentry',
            name='answer',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
