# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-23 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_form_database', '0003_auto_20180321_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedeventformdataentry',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='savedeventformwizarddataentry',
            name='answer',
        ),
    ]
