# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-03 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_form_database', '0004_auto_20180323_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedeventformdataentry',
            name='dragos_saved_data',
            field=models.TextField(blank=True, null=True, verbose_name='Dragos Plugin data'),
        ),
        migrations.AddField(
            model_name='savedeventformwizarddataentry',
            name='dragos_saved_data',
            field=models.TextField(blank=True, null=True, verbose_name='Dragos Plugin data'),
        ),
    ]
