# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-05 16:39
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_form_database', '0010_auto_20180405_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedeventformdataentry',
            name='dragos_q_and_a',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Dragos'),
        ),
        migrations.AddField(
            model_name='savedeventformwizarddataentry',
            name='dragos_q_and_a',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Dragos'),
        ),
    ]
