# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-07 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_form_database', '0011_auto_20180405_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedeventformdataentry',
            name='answers',
            field=models.TextField(blank=True, null=True, verbose_name='Answers'),
        ),
        migrations.AddField(
            model_name='savedeventformdataentry',
            name='questions',
            field=models.TextField(blank=True, null=True, verbose_name='Questions'),
        ),
        migrations.AddField(
            model_name='savedeventformwizarddataentry',
            name='answers',
            field=models.TextField(blank=True, null=True, verbose_name='Answers'),
        ),
        migrations.AddField(
            model_name='savedeventformwizarddataentry',
            name='questions',
            field=models.TextField(blank=True, null=True, verbose_name='Questions'),
        ),
    ]
