# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-10 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_form_database', '0012_auto_20180407_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedeventformdataentry',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='savedeventformdataentry',
            name='dragos_q_and_a',
        ),
        migrations.RemoveField(
            model_name='savedeventformdataentry',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='savedeventformwizarddataentry',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='savedeventformwizarddataentry',
            name='dragos_q_and_a',
        ),
        migrations.RemoveField(
            model_name='savedeventformwizarddataentry',
            name='questions',
        ),
        migrations.AlterField(
            model_name='savedeventformdataentry',
            name='dragos_saved_data',
            field=models.TextField(blank=True, null=True, verbose_name='Dragos Plugin data'),
        ),
        migrations.AlterField(
            model_name='savedeventformwizarddataentry',
            name='dragos_saved_data',
            field=models.TextField(blank=True, null=True, verbose_name='Dragos Plugin data'),
        ),
    ]
