# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-03 20:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import events.models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=256, verbose_name='Event Title')),
                ('event_date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_main_image', imagekit.models.fields.ProcessedImageField(upload_to=events.models.Event.path_and_rename)),
                ('event_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
