# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventdateandtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdateandtime',
            name='event_dateandtime',
        ),
        migrations.AddField(
            model_name='eventdateandtime',
            name='event_end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='End Date and Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventdateandtime',
            name='event_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Date and Time'),
            preserve_default=False,
        ),
    ]
