# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-06 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventdescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_location_name', models.CharField(blank=True, max_length=80, null=True, verbose_name='Name of the location')),
                ('event_location_address', models.CharField(blank=True, max_length=256, null=True, verbose_name='Address of the location')),
                ('event_location_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Date and Time at the location')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_location', to='events.Event')),
            ],
        ),
    ]
