# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-11 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import localized_fields.fields.char_field
import localized_fields.fields.text_field
import localized_fields.fields.uniqueslug_field


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_slug',
            field=localized_fields.fields.uniqueslug_field.LocalizedUniqueSlugField(include_time=False, populate_from='event_title', required=['en'], uniqueness=['en', 'ro']),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_title',
            field=localized_fields.fields.char_field.LocalizedCharField(max_length=256, required=['en'], uniqueness=[], verbose_name='Event Title'),
        ),
        migrations.AlterField(
            model_name='eventdescription',
            name='event_description',
            field=localized_fields.fields.text_field.LocalizedTextField(null=True, required=[], uniqueness=[], verbose_name='Event Description'),
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='event_location_datetime',
            field=models.DateTimeField(blank=True, help_text='This is optional', null=True, verbose_name='Date and Time at the location'),
        ),
    ]
