# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-11 13:13
from __future__ import unicode_literals

from django.db import migrations
import psqlextra.manager.manager


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20180211_1258'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='event',
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
    ]
