# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-11 13:23
from __future__ import unicode_literals

from django.db import migrations
import events.models
import localized_fields.fields.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20180211_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_main_image',
            field=localized_fields.fields.file_field.LocalizedFileField(required=['en'], uniqueness=[], upload_to=events.models.Event.path_and_rename, verbose_name='Main image'),
        ),
    ]
