# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 14:31
from __future__ import unicode_literals

from django.db import migrations
import localized_fields.fields.char_field


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20180211_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlocation',
            name='event_location_name',
            field=localized_fields.fields.char_field.LocalizedCharField(blank=True, max_length=80, null=True, required=[], uniqueness=[], verbose_name='Name of the location'),
        ),
    ]
