# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20180221_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventInvitee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=15, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=50)),
                ('token', models.CharField(blank=True, max_length=15, unique=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='eventinvitee',
            unique_together=set([('event', 'email')]),
        ),
    ]
