# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fobi', '0014_auto_20170516_1413'),
        ('events', '0012_eventfobiforms'),
    ]

    operations = [
        migrations.CreateModel(
            name='FobiTesting',
            fields=[
                ('formentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fobi.FormEntry')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
            bases=('fobi.formentry',),
        ),
    ]
