# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-04 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_fobitesting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_slug',
            new_name='slug',
        ),
    ]
