# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-04 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20180304_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='slug',
            new_name='event_slug',
        ),
    ]
