# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-18 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fobi_contrib_plugins_form_handlers_db_store', '0004_auto_20180313_1446'),
        ('fobi', '0015_auto_20180130_0013'),
        ('events_form_database', '0013_auto_20180410_1938'),
        ('events', '0015_auto_20180304_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFormElementEntry',
            fields=[
                ('formelemententry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fobi.FormElementEntry')),
            ],
            options={
                'abstract': False,
            },
            bases=('fobi.formelemententry',),
        ),
        migrations.CreateModel(
            name='EventFormEntry',
            fields=[
                ('formentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fobi.FormEntry')),
            ],
            bases=('fobi.formentry',),
        ),
        migrations.RemoveField(
            model_name='fobitesting',
            name='event',
        ),
        migrations.RemoveField(
            model_name='fobitesting',
            name='formentry_ptr',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_slug',
            new_name='slug',
        ),
        migrations.DeleteModel(
            name='FobiTesting',
        ),
        migrations.AddField(
            model_name='eventformentry',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event', verbose_name='EventFormEntry'),
        ),
        migrations.AddField(
            model_name='eventformelemententry',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event', verbose_name='EventFormElementEntry'),
        ),
    ]
