# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-23 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20180418_1502'),
        ('invitations', '0002_auto_20180423_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinvitation',
            name='to_email',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.EventInvitee'),
            preserve_default=False,
        ),
    ]
