# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-23 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0003_eventinvitation_to_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinvitation',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventinvitation',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
