# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0004_auto_20180423_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinvitation',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('RO', 'Română')], default='RO', max_length=2),
        ),
    ]
