# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0005_eventinvitation_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventinvitation',
            name='language',
        ),
    ]
